### ISSUE TITLE
Locating an element's label is based on the element's name rather than id

### ISSUE THREAD

**Issue by jkotests** [watir/watir-classic#57]
When locating the label for an element, the element's name attribute is being compared to the label's for attribute. The element's id attribute should be used.

Given the html:

````html
<label for="new_user_first_name" id="first_label">First name</label>
<input name="new_user_first_name" id="new_user_first_name" class="name" />
<label for="new_user_last_name" id="last_label">Last name</label>
<input name="something_else" id="new_user_last_name" class="name" />
````

The correct result when the input name that matches the id:

````ruby
p browser.text_field(:label => 'First name').exists?
#=> true
````

An unexpected result when the input name does not match the id:

````ruby
p browser.text_field(:label => 'Last name').exists?
#=> false
````

**Comment by p0deje** [comment]
That is actually not enough, because by HTML spec the following is also valid:

```html
<label>
  Here goes label
  <input type="text" />
</label>
```

In this case, watir-webdriver can successfully locate element - see watir/watir-webdriver#200 for details and implementation.

Since this is fully tested in watirspec, I believe it makes sense to take a look at http://www.appveyor.com/ and see if it can be used to setup CI for watir-classic.

**Comment by jkotests** [comment]
Thanks @p0deje for pointing that out. There are a couple of problems with how Watir-Classic is currently locating the label. The one you mentioned is covered by Issue #59. As a first release, I was just focusing on addressing some of the smaller bug fixes. After that I was going to work on catching up to the current Watirspec version, which has quite a few changes since the last commit here.

I will take a look into AppVeyor too.
