### ISSUE TITLE
Please release watir-classic 4.0.2

### ISSUE THREAD

**Issue by michaelcm** [watir/watir-classic#74]
Hello,

Would love it if a new gem could be released with the HTML5 compatibility for new input types. If not I'll likely have to clone the code and host internally in a gem in a box server or something.

Thanks in advance!
Michael

**Comment by jkotests** [comment]
Sorry, I had been struggling to get a passing run of the specs, which is why I had not released the earlier fixes. While I am pretty sure the problems were not with the new code, I wanted to be confident things would be working. Then I ran out of time before being able to solve the issue.

I can take another go at it this week. If I am still not successful at getting a passing test run (without manual intervention), I will probably at least release the 4.0.2 in some sort of beta version.

**Comment by michaelcm** [comment]
No problem at all. How does one go about running the specs? I likely have some time as well this week.

**Comment by jkotests** [comment]
The specs are written using RSpec. Assuming you have a clone of the repository, you will simply run `rspec`.

**Comment by michaelcm** [comment]
Gave it a try. Looks like it should be starting up, but forever prints "trying localhost:63420...". Tried under cygwin and cmd and with and without admin rights. Firewall is off. The port seems random so I assumed it is a web server that the run is starting up, and found a second process running spec_helper.rb. I can see that spec_helper.rb is listening on port 63423 not the one we're trying to connect to above (63420). Not sure why.

**Comment by jkotests** [comment]
I got the tests running (with some manual intervention). The tests are either passing or were already failing in v4.0.1.

Version 4.1.0 has been released.

Let me know if there are any issues.
